language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build --no-cache -t cloudqq/privoxy .
  - docker tag cloudqq/privoxy:latest cloudqq/privoxy:v1
  - docker push cloudqq/privoxy
